[package]
authors = ["trevyn <trevyn-git@protonmail.com>"]
description = "Turbocharger full example template with Svelte, Tailwind, and Turbosql."
edition = "2018"
name = "example-full"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/main.rs"

[dependencies]
# dependencies for both server and wasm
turbocharger = {git = "https://github.com/trevyn/turbocharger", branch = "main", version = "0.1"}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# dependencies for wasm only

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# dependencies for server only
opener = "0.5"
rust-embed = "6"
tokio = {version = "1", features = ["full"]}
turbosql = {git = "https://github.com/trevyn/turbosql", branch = "main"}
warp = "0.3"

[patch.crates-io]
js-sys = {git = "https://github.com/Jules-Bertholet/wasm-bindgen", branch = "jsvalue-math"}
rusqlite = {git = "https://github.com/trevyn/rusqlite", branch = "wasm32-unknown-unknown"}
warp = {git = "https://github.com/seanmonstar/warp", branch = "master"}
wasm-bindgen = {git = "https://github.com/Jules-Bertholet/wasm-bindgen", branch = "jsvalue-math"}
wasm-bindgen-futures = {git = "https://github.com/Jules-Bertholet/wasm-bindgen", branch = "jsvalue-math"}
web-sys = {git = "https://github.com/Jules-Bertholet/wasm-bindgen", branch = "jsvalue-math"}
