name: ci

on:
  push:
  pull_request:
  schedule: [cron: '40 2 * * *']

env:
  CARGO_TERM_COLOR: always

jobs:
  checklinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: lycheeverse/lychee-action@v1
        id: lychee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose --no-progress --exclude-all-private --headers="accept=text/html"

      - name: Fail if there were link-check errors
        run: exit ${{ steps.lychee.outputs.exit_code }}

  build:
    name: build ${{ matrix.os }} rust ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-11.0]
        rust: [stable, beta, nightly]

    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: clippy
          targets: wasm32-unknown-unknown

      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: cargo install wasm-bindgen-cli --git https://github.com/rustwasm/wasm-bindgen

      - run: npm run build
      - run: npm audit
      - run: npm run lint
